spring:
  application:
    name: "Job_Search_Java_25"
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

server:
  port: 8888

logging:
  level:
    root: info
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    path: logs